[server]
host = "localhost"
port = 8080
timeout = 30
max_connections = 1000
keep_alive = true

[database]
connection_pool = 50
query_timeout = 5000
retries = 3
backoff_multiplier = 1.5

[metrics]
temperature = 72.5
humidity = 45.2
pressure = 1013.25
altitude = -50

[performance]
cpu = 85.3
memory = 62.8
disk = 45.0
network = 128.5

[build]
version = "2.1.0"
build_number = 12345
pi = 3.14159
e = 2.71828

[array_example]
fibonacci = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

